Fix friendly name and tests simple native phonon
GridPlus/phonon-card pull request #57
Opened 2022-05-04 15:05 UTC by npmaile

2022-05-04 16:33 UTC, maevyn11 requested changes
Looks good mostly, just a couple cleanup things and probably a weird github display issue. Would like Mike's feedback on the pubkey derivation section before merging.

2022-05-04 16:33 UTC, maevyn11 commented on Phonon/src/io/gridplus/phonon/PhononApplet.java
> +        //crypto.sha512.update(ScratchBuffer, (short)1, (short)64);
I don't think we're ever going to put the pubkey back in. It's not additive to the security of the mined phonons and it's inclusion was just causing practical derivation and validation problems. So I think we should just delete this commented out code.

2022-05-04 16:33 UTC, maevyn11 commented on Phonon/src/io/gridplus/phonon/PhononApplet.java
>          // 64 byte of Salt ( TransBuffer ) is private key value
should update comment to say 32 byte

2022-05-04 16:33 UTC, maevyn11 commented on Phonon/src/io/gridplus/phonon/PhononApplet.java
> +            	Util.arrayCopyNonAtomic(PublicKeystr, (short) 0, PhononArray[phononKeyPointer].sPhononPublicKey, (short) 0, PhononArray[phononKeyPointer].PhononPublicKeyLen);
Can see that this works empirically and I think I can trace the code, but damn this is a lot of steps to set a public key in the phonon table. We should def work on wrapping this sort of thing into separate functions post testnet.

2022-05-04 16:33 UTC, maevyn11 commented on Phonon/src/io/gridplus/phonon/PhononApplet.java
> +	}
This code is already in main? 

Not sure what's going on here, has something not been merged. This code is fine, but it's already in the main branch so not sure why this diff is showing up.

2022-05-04 16:33 UTC, maevyn11 commented on Phonon/src/io/gridplus/phonon/SecureChannel.java
> +    public static final boolean USE_CA_DEMO_KEY = true;
Need to flip to false before merging.

2022-05-04 17:14 UTC, SecureElement commented on Phonon/src/io/gridplus/phonon/PhononApplet.java
>          // 64 byte of Salt ( TransBuffer ) is private key value
where is the comment?

2022-05-04 17:15 UTC, SecureElement commented on Phonon/src/io/gridplus/phonon/PhononApplet.java
> +	}
This is work Nate did

2022-05-04 17:19 UTC, SecureElement commented on Phonon/src/io/gridplus/phonon/PhononApplet.java
> +        //crypto.sha512.update(ScratchBuffer, (short)1, (short)64);
I am fine with it.  This is about how you want it to work

2022-05-04 20:35 UTC, maevyn11 commented on Phonon/src/io/gridplus/phonon/PhononApplet.java
>          // 64 byte of Salt ( TransBuffer ) is private key value
line 935 `// 64 byte of Salt ( TransBuffer ) is private key value`

2022-05-06 19:36 UTC, npmaile commented on Phonon/src/io/gridplus/phonon/PhononApplet.java
> +            	Util.arrayCopyNonAtomic(PublicKeystr, (short) 0, PhononArray[phononKeyPointer].sPhononPublicKey, (short) 0, PhononArray[phononKeyPointer].PhononPublicKeyLen);
will do post testnet

2022-05-06 19:36 UTC, npmaile commented on Phonon/src/io/gridplus/phonon/PhononApplet.java
>          // 64 byte of Salt ( TransBuffer ) is private key value
changed.

2022-05-06 19:36 UTC, npmaile commented on Phonon/src/io/gridplus/phonon/PhononApplet.java
> +        //crypto.sha512.update(ScratchBuffer, (short)1, (short)64);
deleted

2022-05-06 19:48 UTC, merged