Updates card-tests
GridPlus/phonon-card pull request #65
Opened 2022-09-22 20:00 UTC by zerodouglas

This PR updates the Go to v1.19, adds a few "if error" blocks, it removes unused variables, and updates the old key index to use the new PhononKeyIndex type, as well as fitting GetName to return an error.

2022-09-22 20:36 UTC, maevyn11 requested changes
Looks like a good straightforward refactor. 

Not sure if we want to change the `replace` directive in go.mod. Otherwise just a couple of opportunities I pointed out to hopefully make the log changes more succinct.

2022-09-22 20:36 UTC, maevyn11 commented on card-tests/main_test.go
> +		t.FailNow()
t.Fatal() would be more succinct instead of both of these lines and is, I think, logically equivalent.

2022-09-22 20:36 UTC, maevyn11 commented on card-tests/main_test.go
> +	t.Logf(fmt.Sprintf("creating %d phonons", len(testPhonons)))
Is the inner fmt.Sprint() call necessary? I thought t.Logf would obey format specifiers the same way.

2022-09-22 20:36 UTC, maevyn11 commented on card-tests/go.mod
> +require (
Do we want to switch from the `replace` directive that looks in the sibling directory? Might make it hard to run these tests when there are breaking changes, for example while cutting over to Beta. I think the method of using whatever client is stored in the sibling works well with the Phonon-Build parent directory, not sure how we would account for this type of change otherwise, I guess we would have to be able to refer to a semantic version for phonon-client and update that here as the client to card API changes.

2022-09-23 17:51 UTC, zerodouglas commented on card-tests/main_test.go
> +		t.FailNow()
Okay, interesting. I removed both lines as suggested and replaced it with t.Fatal() https://github.com/GridPlus/phonon-card/blob/e688fc9904034763f7a9d2302a3f36fd044323e5/card-tests/main_test.go#L311

2022-09-23 17:52 UTC, zerodouglas commented on card-tests/main_test.go
> +	t.Logf(fmt.Sprintf("creating %d phonons", len(testPhonons)))
Ah I missed this. I also updated the rest that had this similarly https://github.com/GridPlus/phonon-card/blob/e688fc9904034763f7a9d2302a3f36fd044323e5/card-tests/main_test.go#L454

2022-09-23 17:53 UTC, zerodouglas commented on card-tests/go.mod
> +require (
As previously discussed, I added Go workspaces :) https://github.com/GridPlus/phonon-card/blob/e688fc9904034763f7a9d2302a3f36fd044323e5/card-tests/go.work

2022-09-23 17:53 UTC, zerodouglas commented on card-tests/go.mod
> +require (
The Go mod also has been updated following this change.

2022-10-31 19:33 UTC, maevyn11 commented
Changes have been rolled into the 'beta' branch under development, therefore closing this.

2022-10-31 19:33 UTC, closed without merging